### ISSUE TITLE
Поправить `pyproject.toml`.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/RandomCoffeeBot#20]
# Why?

Сейчас не собирается приложение...

# How To Do?
Нужно добавить [эту строку](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/blob/develop/pyproject.toml#L7)

# Where?
`pyproject.toml`

**Comment by tmbkv** [comment]
Файл pyproject.toml нормальный. Проблема в файле poetry.lock. Перед сбором проекта помогла команда: poetry lock
В своем текущем PR добавил правильный файл poetry.lock
