### ISSUE TITLE
Добавить Alembic

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/RandomCoffeeBot#26]
# Why?

Alembic - нужен для создания и применения миграций.

# How To Do?

Можно посмотреть [основную настройку в других проектах](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/blob/develop/src/core/db/migrations/env.py). В основном нужно поменять `env.py`

**Comment by tmbkv** [comment]
@NiKuma0 под данной задачей подразумевается инициализация Altembic с созданием каталога Alembic? И в нем уже править env.py?
