### ISSUE TITLE
Починить логгер.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/RandomCoffeeBot#90]
# Why? 

При запуске логгера, падает с ошибкой: 

```
  File "/home/nikuma/.cache/pypoetry/virtualenvs/randomcoffeebot-yT_Tkg51-py3.11/lib/python3.11/site-packages/structlog/stdlib.py", line 1079, in remove_processors_meta
    del event_dict["_record"]
        ~~~~~~~~~~^^^^^^^^^^^
TypeError: 'str' object does not support item deletion
```

# How To Do?

Часть с удалением `event_dict["_record"]` находится в `ProcessorFormatter.remove_processors_meta`. Эта функция нужна, без нее логи выглядят вот так:

![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBot/assets/78080842/5408aa28-2311-402b-b42f-8f3da6909c90)

Тут не очень читабельные данные, и немного бесполезные. `ProcessorFormatter.remove_processors_meta` их должен удалять, но видимо запускается не правильно, потому не работает.

Пару полезных ресурсов:
- [Документация `structlog`](https://www.structlog.org/en/stable/index.html)
- [Пример реализации из другого проекта](https://github.com/Studio-Yandex-Practicum/ProCharity_back_2.0/blob/develop/src/core/logging/setup.py).

# Where?

`src/core/logging.py`

**Comment by LyapkovAleksey** [comment]
@NiKuma0, подскажи, а как вызвать эту ошибку? Что нужно сделать? Я проект у себя локально запустил, у меня логгер отработал без проблем
